server:
  port: 45421
spring:
  application:
    name: photo-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: green
    version: 2